// SPDX-License-Identifier: GPL-2.0-or-later
// ─────────────────────────────────────────────────────────────────
// keymap.c — Vial default keymap
// Generated by QMK/Vial Wizard v5.6 on 2026-09-03
// ─────────────────────────────────────────────────────────────────
//
// This is a starting point — a basic QWERTY layout.
// You should remap keys using the Vial GUI after flashing.
// Vial stores your remapped layout in the keyboard's EEPROM,
// so you only need to reflash when changing features, not keycodes.
//
// HOW LAYERS WORK:
// Layer 0 is always active (base layer). Higher-numbered layers
// override lower ones when activated by a layer-switch key (MO, TG, etc).
// KC_TRNS on an upper layer means "fall through to the layer below".
// KC_NO on any layer means "do nothing / no keypress".
//
// MATRIX DIMENSIONS: 4 rows × 13 cols
// (Single board: 4 rows)
//
#include QMK_KEYBOARD_H

// 1. Properly initialized placeholder combo structure 
const uint16_t PROGMEM placeholder_combo[] = {KC_A, KC_B, COMBO_END};
combo_t key_combos[COMBO_COUNT] = {
    COMBO(placeholder_combo, KC_NO) // Set to KC_NO so it doesn't physically trigger anything
};

// 2. Properly initialized placeholder Tap Dance structure
tap_dance_action_t tap_dance_actions[] = {
    = ACTION_TAP_DANCE_FN(NULL)
};

// Your existing 45-key keymaps layers array goes directly below...
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        /* Row 0: 12 keys */
        KC_ESC,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC,
        
        /* Row 1: 12 keys */
        KC_TAB,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
        
        /* Row 2: 13 keys */
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_UP,   KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT,
        
        /* Row 3: 8 keys */
        KC_LCTL, KC_LGUI, KC_LALT, KC_SPC,  KC_LEFT, KC_DOWN, KC_RGHT, MO(1)
    ),
    [1] = LAYOUT(
        /* Row 0: 12 keys */
        KC_TRNS, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL,
        /* Row 1: 12 keys */
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_BSLS,
        /* Row 2: 13 keys */
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        /* Row 3: 8 keys */
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    )
};
